### ISSUE TITLE
question about globals in `@serwist/core` and `globals.d.ts`

### ISSUE THREAD

**Issue by userquin** [serwist/serwist#132]
The dts is not included in the final package and it is not included in the subpackage exports, shouldn't it be in the distribution and included?

**Comment by DuCanhGH** [comment]
@userquin ah, well, that file is only meant for development purposes. We expect the users to extend `SerwistGlobalConfig` themselves. Well, for now, at least.

Though, since that is only for development, I wonder if we should move the file up from the package. That would cause inspecting the shipped source code to show some more red squiggles though.

**Comment by userquin** [comment]
@DuCanhGH FYI: you can enable `shell-emulator=true` in `.npmrc` file and remove `cross-env` dev dependency and update all scripts using it, just declare env variables without `cross-env` prefix` (all platforms): https://pnpm.io/cli/run#shell-emulator

**Comment by DuCanhGH** [comment]
@userquin huh, thanks for the info :) Will investigate soon!
