### ISSUE TITLE
[Improvement] Update types for `SerwistPlugin` callback params

### ISSUE THREAD

**Issue by JoseVSeb** [serwist/serwist#162]
The type of `event` property in `SerwistPlugin` callback params is currently `ExtendableEvent`. Wouldn't `FetchEvent` be better suited?

e.g. `RequestWillFetchCallbackParam` always give `FetchEvent` https://github.com/serwist/serwist/blob/353cadecd70ec1e2304df1339eb80b6a16a8de89/packages/core/src/types.ts#L211

**Comment by DuCanhGH** [comment]
Not really. The `install` event, during which we precache assets via `Strategy.handleAll`, which passes the event to lifecycle callbacks (it's actually `StrategyHandler`, but let's skip the technical details), provides an `ExtendableEvent` event rather than a `FetchEvent` one. This means that we can't assume that the event is always a `FetchEvent` one. Now, of course, we can use `ExtendableEvent | FetchEvent` instead, but you will have to use `event instanceof FetchEvent` all the same anyway, so that won't help much.
