### ISSUE TITLE
[Docs]: Testing with nextjs

### ISSUE THREAD

**Issue by elsigh** [serwist/serwist#186]
### Provide environment information

"@serwist/next": "^9.0.2"

### Describe the problem

What are the best ways to test service worker behavior?

### Expected behavior

Docs about how to test/reload with different sw.ts logic

### Additional information (if relevant)

I haven't tried messing with my service worker configuration / cache handling in a while but now I want to again and can't remember the right workflow

**Comment by DuCanhGH** [comment]
To be honest, I'm not sure about how we'd test service workers' behaviour, either. This is why I haven't written more than a few tests for Serwist just yet - Workbox's test suite consisted of way too many tests, some... rather not helpful in my opinion. But I guess you can take some reference from Workbox's way of doing things.

If I had to guess, you'd use Puppeteer, Playwright, or whatever headless browser you prefer, along with a testing framework like Vitest or Jest. Not sure how useful that'd be though. For simpler use cases, you can just... well, test it yourself with a browser™️ 😅 Testing offline functionality would require you to build your application in production mode though.

**Comment by elsigh** [comment]
I actually only really mean that last example you mentioned - that in order to test you need to `next build` and `next start` and then open devtools to the Application tab and then monitor Network requests etc etc. Honestly I think that's a blog post and while it's not unique to @serwist/next it's a DX opportunity to be able to guide people to a happy path. 

btw afaik right now you can only regenerate the sw.js file with a full `next build` - I wonder if there's a faster way to be able to iterate just on the sw.ts -> sw.js file in the build directory experience?

**Comment by DuCanhGH** [comment]
@elsigh 

> btw afaik right now you can only regenerate the sw.js file with a full `next build` - I wonder if there's a faster way to be able to iterate just on the sw.ts -> sw.js file in the build directory experience?

Wait, that doesn't seem right. Shouldn't the development service worker be generated whenever you update your source service worker? I mentioned using `next build` to test because in development, `@serwist/next` sets `defaultCache` to an array that only contains a network-only entry, preventing the service worker from caching anything that is meant to be up-to-date such as JS files. Well, to be honest, I'm not sure about whether we should do it this way though. Chrome specifically has the Offline, Upload on reload, Bypass for network options to help us debug service workers in development. Not really so when it comes to Firefox though. 

According to Chrome for Developers, the most effective way to test service workers is... using private browsing windows:

> Local development with a service worker in the mix can lead to seemingly unexpected behaviors. For example, let's say a cache-only strategy is in place for unversioned static assets, or a precached "you're offline" page that's expected to update on reload after making changes. Because a stale version of those assets are always being served from a Cache instance, they seemingly never update! Frustrating as this is, the service worker is only doing what it was built to do, but there are some ways to make testing easier.
>
> By far the most effective way to test a service worker is to rely on private browsing windows, such as incognito windows in Chrome, or Firefox's Private Browsing feature. Every time you open a private browsing window, you start fresh. There are no active service workers, and no open Cache instances. The routine for this kind of testing is:
>
> 1. Open a private browsing window.
>
> 1. Navigate to a page that registers a service worker.
>
> 1. Verify if the service worker behaves as you expect.
>
> 1. Close the incognito window.
>
> 1. Repeat.

I guess we can think about changing `defaultCache` in near future to accomodate testing in development. Not sure how we'd go about not causing the content to be stale without having to outright tell people to use Chrome's Bypass for network option though. And then we'd have to think about poor Firefox users like me 😅

**Comment by elsigh** [comment]
Even that information was helpful to me. Even linking out to wherever you got that text from would be nice.

It still feels suspect to me that Chrome gets into terrible states while testing my service worker not in an incognito tab.

**Comment by DuCanhGH** [comment]
@elsigh 

> Even that information was helpful to me. Even linking out to wherever you got that text from would be nice.

[Here you go](https://developer.chrome.com/docs/workbox/improving-development-experience) :)

> It still feels suspect to me that Chrome gets into terrible states while testing my service worker not in an incognito tab.

I'm not sure what that means, unfortunately...
