### ISSUE TITLE
[Bug]: No import.meta.env inside service worker file when custom vite envPrefix and envDir are used.

### ISSUE THREAD

**Issue by minht11** [serwist/serwist#214]
### Provide environment information

I have monorepo project with single env file at the root so my vite config looks something like this:
```ts
{
	envDir: join(import.meta.dirname, '../../'),
	envPrefix: 'PUBLIC_',
}
```

The 

### Which project is this issue for?

@serwist/vite

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

n/a

### To reproduce

Run serwist where envDir is not the default.

### Describe the bug

No env variables inside service worker file when envDir option is used. 

### Expected behavior

import.meta.env resolved variables correctly.

**Comment by DuCanhGH** [comment]
This has been fixed in `vite-plugin-serwist@9.1.0-preview.0` :) Note that the package has been renamed from `@serwist/vite` to `vite-plugin-serwist`. It's a small fix, but since it's a part of a bigger update to Serwist's Vite plugin, it's temporarily only available on the preview builds for now.

Really surprised that someone actually uses `vite-plugin-serwist` though! Thanks!
